# Your Twilio Account SID. Get a free account at twilio.com/try-twilio
TWILIO_ACCOUNT_SID=AC6c7c7b24e9ef4b6090c9ddcf9a76ef25
# Your Twilio Auth Token. You can get it at twilio.com/console
TWILIO_AUTH_TOKEN=0261532a78b2383d68581acacbe85b23
# The Twilio phone number you want to use to send SMS. Get one in the Twilio Console
TWILIO_PHONE_NUMBER=+12244133545
