name: Spring CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [ 8, 8.0.192, 9.0.x, 10, 11.0.x, 11.0.3, 12, 13 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle (Linux / Mac)
        if: runner.os == 'Linux' || runner.os == 'macOs'
        run: ./gradlew build
      - name: Build with Gradle (Windows)
        if: runner.os == 'Windows'
        run: gradlew.bat build
      - name: Run tests (Linux / Mac)
        if: runner.os == 'Linux' || runner.os == 'macOs'
        run: ./gradlew test
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: gradlew.bat test
