name: Spring CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.json'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.json'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build with Gradle (Linux / Mac)
        if: runner.os == 'Linux' || runner.os == 'macOs'
        run: ./gradlew build
      - name: Build with Gradle (Windows)
        if: runner.os == 'Windows'
        run: .\gradlew.bat build
